### ISSUE TITLE
Move to Redis

### ISSUE THREAD

**Issue by Ovyerus** [Ovyerus/knife-bot#17]
Using Redis could have some speed benefits for the bot, as well as being able to have it handle caching instead of having to do it ourselves. Also I believe that more platforms have support for Redis over Rethink.

**Comment by H3xadecimal** [comment]
Oh boy... Welcome to the Redis club.

**Comment by Ovyerus** [comment]
Deciding to use [Rebridge](https://github.com/CapacitorSet/rebridge) for this as it supports Promises out of the box, and has a nice and simple API for setting and getting objects from the database.

**Comment by Ovyerus** [comment]
May actually use [ioredis](https://github.com/luin/ioredis) as it only needs me to have one dependency for Redis, as well as support for Pub/Sub if I ever need it and it seems to be somewhat similar to rethinkdbdash.

**Comment by Ovyerus** [comment]
Currently testing implementation.

**Comment by Ovyerus** [comment]
Done in bbca70e
